version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CONFIG: production  # development (en local) ou production(pour push en ligne)
    ports:
      - "4200:80"


networks:
  app-network:
    driver: bridge

