version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: development  # change à 'production' pour un build prod
    ports:
      - "4200:4200"  # ou "80:80" si tu utilises la prod/NGINX
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

