version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CONFIG: development  # development (en local) ou production (en ligne)
    ports:
      - "4200:80"
    networks:
      - app-network

  ia:
    build:
      context: ./ia_pandemie
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
>>>>>>>>> Temporary merge branch 2
      - app-network

networks:
  app-network:
    driver: bridge
