name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: 🧾 Récupération du code
      uses: actions/checkout@v3

    - name: 🔧 Installation backend
      working-directory: backend
      run: |
        npm install

    - name: ✅ Lancer les tests backend
      working-directory: backend
      run: |
        npm test || echo "Pas de tests encore définis"

    - name: 🧪 Build frontend
      working-directory: frontend
      run: |
        npm install
        npm run build -- --configuration=production
